Fix build when dired disabled
troglobit/mg pull request #23
Opened 2024-02-11 14:03 UTC by g-branden-robinson

* src/def.h:
* src/dired.c:
* src/funmap.c:
* src/keymap.c: Guard references to `dired_jump` function and its implementation behind `ENABLE_DIRED` preprocessor maco.

Fixes linker error when building with `--disable-dired` configuration option and those that imply it.

2024-02-11 14:06 UTC, g-branden-robinson commented
You might also be interested in or amused by [my  own `mg` fork](https://github.com/g-branden-robinson/mg/tree/gbr).

FYI, that branch gets force-pushed frequently.

2024-02-18 11:05 UTC, troglobit requested changes
Looks good, except for those first two patches (not needed).

2024-02-18 11:05 UTC, troglobit commented on src/def.h
> +#endif
Not needed.

2024-02-18 11:05 UTC, troglobit commented on src/dired.c
> +#endif
Also not needed, the file is not build with `--disable-dired`.

2024-02-18 11:11 UTC, troglobit commented
> You might also be interested in or amused by [my own `mg` fork](https://github.com/g-branden-robinson/mg/tree/gbr).

Interesting!  Only browsed through it quickly, but I'll probably go back and port a few things to my fork when I circle back to the next release cycle :-)

2024-02-18 15:24 UTC, troglobit approved these changes

2024-02-18 18:15 UTC, merged